
spring:
  datasource:
          name: test
          url: jdbc:mysql://182.61.166.15:3306/test?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF8
          username: mytest
          password: mytest
          driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8888
jwt:
  secret: