spring:
  datasource:
          name: test
          # url: jdbc:mysql://182.61.166.15:3306/test?useUnicode=true&characterEncoding=UTF8
          url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF8
          username: mytest
          password: mytest
          driver-class-name: com.mysql.cj.jdbc.Driver


server:
  port: 8081
  servlet:
    context-path: /

mpstore:
  service-url: http://localhost:${server.port}${server.servlet.context-path}
  file:
     upload-path: D:/upload
