spring:
  datasource:
          name: test
          url: jdbc:mysql://182.61.166.15:3306/test?useUnicode=true&characterEncoding=UTF8
          username: mytest
          password: mytest
server:
  port: 8081
  servlet:
    context-path: /mpadmin

mpstore:
  file:
     upload-path: D:/upload
